# Configuración de Cloud Build para DocuValle
# Este archivo coordina el despliegue completo del frontend y backend

steps:
  # PASO 1: Instalar dependencias del backend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'backend'
    id: 'install-backend-deps'

  # PASO 2: Compilar el backend TypeScript a JavaScript
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'backend'
    id: 'build-backend'
    waitFor: ['install-backend-deps']

  # PASO 3: Construir la imagen Docker del backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/apt-cubist-368817/docuvalle-backend/backend:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/apt-cubist-368817/docuvalle-backend/backend:latest',
      './backend'
    ]
    id: 'build-docker-image'
    waitFor: ['build-backend']

  # PASO 4: Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/apt-cubist-368817/docuvalle-backend/backend']
    id: 'push-docker-image'
    waitFor: ['build-docker-image']

  # PASO 5: Desplegar backend a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'docuvalle-backend',
      '--image', 'us-central1-docker.pkg.dev/apt-cubist-368817/docuvalle-backend/backend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production,PROJECT_ID=apt-cubist-368817'
    ]
    id: 'deploy-backend'
    waitFor: ['push-docker-image']

  # PASO 6: Instalar dependencias del frontend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'
    id: 'install-frontend-deps'

  # PASO 7: Construir el frontend React optimizado para producción
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    id: 'build-frontend'
    waitFor: ['install-frontend-deps']
    env:
      - 'REACT_APP_API_URL=https://docuvalle-backend-775139116207.us-central1.run.app'
      - 'REACT_APP_PROJECT_ID=apt-cubist-368817'

  # PASO 8: Desplegar frontend a Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting', '--project', 'apt-cubist-368817']
    id: 'deploy-frontend'
    waitFor: ['build-frontend']

# Configuraciones adicionales
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Variables de entorno que Cloud Build necesita
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'docuvalle-backend'
  _REPOSITORY: 'docuvalle-backend'

timeout: '1200s'